spring.application.name=autenticacionservice
server.port=8086

# Base de datos propia para este servicio
spring.datasource.url=jdbc:mysql://localhost:3306/db_autenticacion?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Llave secreta para firmar el token (debe ser IGUAL a la del api-gateway)
jwt.secret=PerfumeriaTomasGonzalez2026ClaveSecretaJWTMinimo32Caracteres

# Swagger / OpenAPI
springdoc.api-docs.path=/api/v1/autenticacion/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
